version: '2'

services:

  wordpress:
    image: wordpress:4.7.0-apache
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: DEFAULT

  mysql:
    image: mariadb:10.1.19
    ports:
      - 8081:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: DEFAULT
